# Generated by Django 3.2.23 on 2024-01-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacapp', '0002_alter_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='card',
            field=models.IntegerField(default=0),
        ),
    ]
